### ISSUE TITLE
Locations of Google Maps to download images(shp file)

### ISSUE THREAD

**Issue by liyang-7** [carsonluuu/Poverty-Prediction-by-Satellite-Imagery#1]
Could you provide the 'Sector_Boundary_2012.shp' file in the code? Due to our regional network, we can't download it. Thank you very much!!! My Email: liyang415@mails.ucas.ac.cn

**Comment by am-sirdaniel** [comment]
Could you please provide the *image_loc.csv** & **features_all_predict.csv** file or how to generate them in the code? I'll appreciate your prompt response. My Email is Ajisafedaniel@gmail.com

**Comment by carsonluuu** [comment]
> Could you provide the 'Sector_Boundary_2012.shp' file in the code? Due to our regional network, we can't download it. Thank you very much!!! My Email: [liyang415@mails.ucas.ac.cn](mailto:liyang415@mails.ucas.ac.cn)

Uploaded and mailed to you.
